config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  resources :files

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  namespace :admin do
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true

  has_many :permissions, :as => :thing
  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view",
        :user_id => user.id })
  }
 
  has_many :tickets

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :check_for_sign_up
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user).all
  end
  
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

private
  def find_project
    @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" + " for could not be found."
    redirect_to projects_path
  end

  def check_for_sign_up
    if request.referer == user_registration_url
      redirect_to confirm_user_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label      :name, "Project name" %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>
 

app/views/projects/index.html.erb
<%= admins_only do %>
 <%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul id='projects'>
  <% for project in @projects %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>
 

app/views/projects/new.html.erb
<h2>New project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<h2><%= @project.name %></h2>

<title>
 <% if content_for?(:title) %>
   <%= yield(:title) %>
 <% else %>
   Ticketee
 <% end %>
</title>
        
<%= admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>

  <%= link_to "Delete Project", @project, :method => :delete,
   :confirm => "Are you sure you want to delete this project?" %>
<% end %>

<%= authorized?("create tickets".to_sym, @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
  <li>
    <%= render ticket.state if ticket.state %>
    #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
  </li>
  <% end %>
</ul>
######################################################################

 