config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  resources :files

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  namespace :admin do
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root :to => "projects#index"

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
    :to => 'admin/permissions#update',
    :as => :update_user_permissions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Ticketee" %></title>
  <nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
  <%= admins_only do %>
    <%= link_to "Admin", admin_root_path %><br>
  <% end %>
  </nav>
  <%= stylesheet_link_tag    "application" %>
  <style>
    <% for state in @states %>
      .state_<%= state.name.parameterize %> {
        background: <%= state.background %>;
        color: <%= state.color %>;
      }
    <% end %>
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
  <%= value %>
  </div>
<% end %>

<h1><%= link_to "Ticketee", root_path %></h1>
<%= yield %>

</body>
</html>